name: Merge to store themes
 
on:
 push:
   branches:
     - online
   paths-ignore:
     - 'templates/*.json'
     - 'config/*.json'
 pull_request:
   branches:
     - online
   paths-ignore:
     - 'templates/*.json'
     - 'config/*.json'
